//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripAdv.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityActivityTypeMap
    {
        public int ActivityActivityTypeMapID { get; set; }
        public int ActivityID { get; set; }
        public int ActivityTypeID { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual ActivityType ActivityType { get; set; }
    }
}
