//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripAdv.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityRating
    {
        public int ActivityRatingId { get; set; }
        public int ActivityId { get; set; }
        public int UserId { get; set; }
        public int Points { get; set; }
        public string Description { get; set; }
    }
}
