//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripAdv.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActivityType()
        {
            this.ActivityActivityTypeMaps = new HashSet<ActivityActivityTypeMap>();
            this.ActivityType1 = new HashSet<ActivityType>();
        }
    
        public int ActivityTypeID { get; set; }
        public string Name { get; set; }
        public string IconURL { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string GoogleCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityActivityTypeMap> ActivityActivityTypeMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityType> ActivityType1 { get; set; }
        public virtual ActivityType ActivityType2 { get; set; }
    }
}
