//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripAdv.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int LoginId { get; set; }
        public string Token { get; set; }
        public System.DateTime LastHit { get; set; }
        public int UserId { get; set; }
    
        public virtual Login Login1 { get; set; }
        public virtual Login Login2 { get; set; }
        public virtual User User { get; set; }
    }
}
